### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by EduardoRodriguesF** [EduardoRodriguesF/quartz#14]
Projects and users should have a way to save variables in environments. This would make switching between differnet parametized routes easy.

The syntax in the toml files should be as such:

```toml
url = "https://{{account}}.vtex.com/example"
method = "GET"
```

The `{{ }}` wrapper indicates a variable and should be empty if no variables matches it.

Not sure yet if variable files should be in .toml or .json though.
